### PR TITLE
Update tw.h

### PR DESCRIPTION
**Pull request by lineteen**
Translate from Simplified Chinese.

---
This change is [Reviewable](https://reviewable.io/reviews/grayhatter/utox/264)

### CODE REVIEW

**Comment by GrayHatter** [comment]
:lgtm:

@lineteen thanks mate this looks good. As soon as anyone else looks at it and says it's okay, I'll merge it.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/grayhatter/utox/264#-:-KEDoXUU2HCOEf6LmuP_:-538312687)*

**Comment by GrayHatter** [comment]
:lgtm: @stal888 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/grayhatter/utox/264#-:-KFFx_GkC3MLeRsFswZ8:1686745061)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/grayhatter/utox/264)*

**Comment by stal888** [comment]
Your rubber stamp is here: :lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/grayhatter/utox/264#-:-KFGEKglqXKAL1fEBCiq:912831187)*

**Comment by GrayHatter** [comment]
sorry about the delay @lineteen thanks for the translations

**Pull request merged**
