### PR TITLE
Russian translation updated

### PR DESCRIPTION
**Pull request by ingvar1995**
first part of my commits - Russian translation updated

### CODE REVIEW

**Comment by ingvar1995** [comment]
"Не беспокоить", "Отошёл" is unused at all. Покинуть -> удалить (you can leave group without deleting it, so I used "Leave"), "Удалить друга" - from eng "remove friend". "Никнейм" is more popular than "Псевдоним", but this is not russian word, you are right

**Comment by czarkoff** [comment]
"Покинуть" is appropriate for "LEAVE_GROUP", but is not for "REMOVE_GROUP".

**Comment by ingvar1995** [comment]
! also come from en.h. BTW that 2 strings is also unused now as I can see

**Comment by czarkoff** [comment]
FWIW you are not supposed to perform literal translation; you are supposed to localize, to bring in line with local convention. Phrase "Удалить друга" has no right to exist in Russian text - these words just don't fit together. Albeit word "никнейм" is spreading as cancer, you are not required to use it, particularly if there is equivalent word that is absolutely appropriate. Exclamation mark in Russian UI is used to denote dangerous actions like detonation or rocket launch, and is inappropriate for command with no harmful side effect.

**Comment by GrayHatter** [comment]
ping me when you guys reach a concensus and I'll merge this. 

@czarkoff I haven't forgotten about you PR, I'm just really busy lately

**Pull request closed without merging**
