### PR TITLE
cocoa: add tox: url handling and limit window size

### LINKED ISSUE #289: OSX: resizing window too small
If I attempt to resize the window and it's too small, then utox will crash.

`2016-04-11 21:05:55.431 utox[2305:251476] warning: space given not enough for drawtextwidth, bailing`

alt text

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/32850086-osx-resizing-window-too-small?utm_campaign=plugin&utm_content=tracker%2F21546874&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F21546874&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by stal888**
fixes #289 and #286.

---
This change is [Reviewable](https://reviewable.io/reviews/grayhatter/utox/290)

### CODE REVIEW

**Comment by GrayHatter** [comment]
will test soon, see other comments

---

Reviewed 6 of 8 files at r1.
Review status: 6 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/commands.c, line 88 \[r1\]](https://reviewable.io:443/reviews/grayhatter/utox/290#-KFFh1FwZQTvAG1ym9S1:-KFFh1FwZQTvAG1ym9S2:-352220510) ([raw file](https://github.com/grayhatter/utox/blob/63e75d1172fdb7f258d83d7faab4c5beb347857c/src/commands.c#L88)):*
does anyone use this format?

Can we drop it?

---

*[src/tox.c, line 1359 \[r1\]](https://reviewable.io:443/reviews/grayhatter/utox/290#-KFFhSMsx8uEhH2vCIIY:-KFFhSMsx8uEhH2vCIIZ:818625633) ([raw file](https://github.com/grayhatter/utox/blob/63e75d1172fdb7f258d83d7faab4c5beb347857c/src/tox.c#L1359)):*
are you sure this is the best way?

i.e., are you happy with doing it this way?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/grayhatter/utox/290#-:-KFFiogBRpoxl86zgM9s:265045605)*

**Comment by GrayHatter** [comment]
Review status: 6 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/commands.c, line 126 \[r1\]](https://reviewable.io:443/reviews/grayhatter/utox/290#-KFFj016WOqtjOWJG5Ok:-KFFj017PiRELGKhmSGT:127116805) ([raw file](https://github.com/grayhatter/utox/blob/63e75d1172fdb7f258d83d7faab4c5beb347857c/src/commands.c#L126)):*
from @Impyy https://github.com/Tox-Archive/Tox-STS/blob/master/STS.md#dns-discovery

@stal888 think we can just drop this then?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/grayhatter/utox/290)*

**Comment by Impyy** [comment]
You can drop the tox2 stuff. There's no tox dns service that supports that anymore.

**Comment by stal888** [comment]
*[src/commands.c, line 88 \[r1\]](https://reviewable.io:443/reviews/grayhatter/utox/290#-KFFh1FwZQTvAG1ym9S1:-KFFlymAVm1l6xVlasUq:-523737591) ([raw file](https://github.com/grayhatter/utox/blob/63e75d1172fdb7f258d83d7faab4c5beb347857c/src/commands.c#L88)):*
I think tox://, tox:, and tox:/// were all used at some point

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/grayhatter/utox/290)*

**Comment by stal888** [comment]
*[src/commands.c, line 126 \[r1\]](https://reviewable.io:443/reviews/grayhatter/utox/290#-KFFj016WOqtjOWJG5Ok:-KFFm4LfS69lItvdpin9:678041242) ([raw file](https://github.com/grayhatter/utox/blob/63e75d1172fdb7f258d83d7faab4c5beb347857c/src/commands.c#L126)):*
sure

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/grayhatter/utox/290)*

**Comment by stal888** [comment]
*[src/tox.c, line 1359 \[r1\]](https://reviewable.io:443/reviews/grayhatter/utox/290#-KFFhSMsx8uEhH2vCIIY:-KFFmbgFF4uNYfE3J0TM:2135895354) ([raw file](https://github.com/grayhatter/utox/blob/63e75d1172fdb7f258d83d7faab4c5beb347857c/src/tox.c#L1359)):*
We can potentially piggyback on this message later. In fact we could probably get rid of UPDATE_TRAY as well

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/grayhatter/utox/290)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 8 files at r1.
Review status: 7 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/commands.c, line 88 \[r1\]](https://reviewable.io:443/reviews/grayhatter/utox/290#-KFFh1FwZQTvAG1ym9S1:-KFFoIGOcB9t213Pf9xM:184645510) ([raw file](https://github.com/grayhatter/utox/blob/63e75d1172fdb7f258d83d7faab4c5beb347857c/src/commands.c#L88)):*
So you still want to keep that format?

Your call, I'm okay with either

---

*[src/commands.c, line 126 \[r1\]](https://reviewable.io:443/reviews/grayhatter/utox/290#-KFFj016WOqtjOWJG5Ok:-KFFoYynB4seoGOGiILx:-1076513138) ([raw file](https://github.com/grayhatter/utox/blob/63e75d1172fdb7f258d83d7faab4c5beb347857c/src/commands.c#L126)):*
agreed, and per @impyy -> delete the pin section

---

*[src/tox.c, line 1359 \[r1\]](https://reviewable.io:443/reviews/grayhatter/utox/290#-KFFhSMsx8uEhH2vCIIY:-KFFni0PHOZthU7ixITF:105451805) ([raw file](https://github.com/grayhatter/utox/blob/63e75d1172fdb7f258d83d7faab4c5beb347857c/src/tox.c#L1359)):*
I'd rather leave update tray in for now. There's still some outstanding issues that need to be solved. Removing may be the best idea, but I don't how to best solve them all so don't want to do anything on that yet.

That's a good idea, we can use this to do things once the tox instance comes up. Like kickoff AV threading and $OTHER.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/grayhatter/utox/290)*

**Comment by stal888** [comment]
*[src/commands.c, line 88 \[r1\]](https://reviewable.io:443/reviews/grayhatter/utox/290#-KFFh1FwZQTvAG1ym9S1:-KFFtwMTDJ5m7XdT2nby:-499146009) ([raw file](https://github.com/grayhatter/utox/blob/63e75d1172fdb7f258d83d7faab4c5beb347857c/src/commands.c#L88)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/grayhatter/utox/290)*

**Comment by stal888** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/commands.c, line 126 \[r1\]](https://reviewable.io:443/reviews/grayhatter/utox/290#-KFFj016WOqtjOWJG5Ok:-KFFu3ZAmX-OYsQHfXSb:-499146009) ([raw file](https://github.com/grayhatter/utox/blob/63e75d1172fdb7f258d83d7faab4c5beb347857c/src/commands.c#L126)):*
Done.

---

*[src/tox.c, line 1359 \[r1\]](https://reviewable.io:443/reviews/grayhatter/utox/290#-KFFhSMsx8uEhH2vCIIY:-KFFu6Pq5HlpU5dUZEJJ:-662986187) ([raw file](https://github.com/grayhatter/utox/blob/63e75d1172fdb7f258d83d7faab4c5beb347857c/src/tox.c#L1359)):*
I'll keep it the way it is then

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/grayhatter/utox/290)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/grayhatter/utox/290#-:-KFFuTscpix1iyQncTIU:1417088721)*

**Pull request merged**
