### PR TITLE
Fix for issue #237 mouse wheel scroll is very slow

### PR DESCRIPTION
**Pull request by master-passeli**
Patch fixes issue #237  where mouse scroll is very slow on scrollable viewport
components. Patch introduces scroll speed multiplier variable which can
be used to tune scrolling speed. This variable influences "magic"
equation in scrollable component.
The patch speeds up scrolling making it 5 times faster. By doing that
it brings scrolling behavior closer to other programs.
However, current implementation does not allow similar scrolling behavior since uTox's 
GUI implementation is not text size relative.

---
This change is [Review on Reviewable](https://reviewable.io/reviews/grayhatter/utox/241)

### CODE REVIEW

**Comment by GrayHatter** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/grayhatter/utox/241#-:-KCflnwIJ5muIWxe1l8G:1417088721)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/grayhatter/utox/241)*

**Comment by tsudoko** [comment]
Works on xlib

**Comment by GrayHatter** [comment]
stal broke it for cocoa, he can fix it later

**Pull request merged**
