### PR TITLE
ToxAV new api.

### PR DESCRIPTION
**Pull request by GrayHatter**
Update to the new toxcore AV api.

This branch will not work with clients on the old API.

### CODE REVIEW

**Comment by GrayHatter** [comment]
Merging on 2015-10-23 with the new toxcore ToxAV API

**Comment by irungentoo** [comment]
Things not working in uTox:

1. Video preview button in uTox is dead when not in call
2. When video calling receiver crashes because of an X error (Details: serial 69432 error_code 2 request_code 1 minor_code 0)
3. After receiver crashes, sender freezes because of deadlock because of:

```
Thread 8 (Thread 0x7ffff79b1700 (LWP 11704)):
#0  0x000000300c4b932d in nanosleep () from /lib64/libc.so.6
#1  0x000000300c4e0c54 in usleep () from /lib64/libc.so.6
#2  0x00000000005bc993 in yieldcpu (ms=1) at ./xlib/main.c:446
#3  0x0000000000697e3a in tox_postmessage (msg=27 '\033', param1=0, param2=1, data=0x0) at tox.c:258
#4  0x0000000000b96859 in utox_av_remote_disconnect (av=0x60f000007750, friend_number=0) at utox_av.c:57
#5  0x0000000000b930dc in utox_callback_av_change_state (av=0x60f000007750, friend_number=0, state=1, userdata=0x0)
    at utox_av.c:181
#6  0x00000000010d1447 in invoke_call_state_callback (av=0x60f000007750, friend_number=0, state=0) at ../toxav/toxav.c:990
#7  0x00000000010c3d14 in callback_error (toxav_inst=0x60f000007750, call=0x60400023dfd0) at ../toxav/toxav.c:944
#8  0x00000000010dbc4e in invoke_callback (call=0x60400023dfd0, cb=<optimized out>) at ../toxav/msi.c:481
#9  0x00000000010d6cd8 in on_peer_status (m=<optimized out>, friend_number=<optimized out>, status=0 '\000', 
    data=0x60c000005980) at ../toxav/msi.c:612
#10 0x000000000111a8e3 in check_friend_connectionstatus (friendnumber=-140904560, status=3 '\003', m=<optimized out>)
    at ../toxcore/Messenger.c:882
#11 set_friend_status (m=0x61f00001ea80, friendnumber=-140904560, status=3 '\003') at ../toxcore/Messenger.c:889
#12 0x0000000001120336 in handle_status (object=0x61f00001ea80, i=0, status=<optimized out>) at ../toxcore/Messenger.c:1901
#13 0x00000000011b3f88 in handle_status (object=<optimized out>, number=<optimized out>, status=0 '\000')
    at ../toxcore/friend_connection.c:342
#14 0x00000000011b2308 in do_friend_connections (fr_c=<optimized out>) at ../toxcore/friend_connection.c:832
#15 0x000000000111ba27 in do_messenger (m=<optimized out>) at ../toxcore/Messenger.c:2320
#16 0x0000000001128749 in tox_iterate (tox=0x61f00001ea80) at ../toxcore/tox.c:405
#17 0x0000000000699dd8 in tox_thread (UNUSED_args=<optimized out>) at tox.c:589
#18 0x000000300d008204 in start_thread () from /lib64/libpthread.so.0
#19 0x000000300c4e746d in clone () from /lib64/libc.so.6
```
Message from the Tox thread to the tox thread?

**Comment by benwaffle** [comment]
When I try to make a call, http://fpaste.org/282991/14733144/

**Comment by GrayHatter** [comment]
@benwaffle can you make it happen every time?

**Comment by GrayHatter** [comment]
@irungentoo fixed both issues, 

but @benwaffle @irungentoo  I couldn't and get utox to crash, so I'm going to need some more information clients? client versions? who's calling? OS? window manager? version?

**Comment by benwaffle** [comment]
arch linux, gnome 3.18, I'll try to reproduce

**Pull request merged**
