### PR TITLE
refactor list searching & filtering, and add previous/next tab shortcuts on Linux and Windows

### PR DESCRIPTION
**Pull request by Doom032**
Sorry for the amount of changes. All I wanted to do is add ctrl+[shift+]tab, ctrl+pgup and ctrl+pgdn for going through the list of friends. Then I found it wasn't easy to do with the weird way filtering and searching was implemented(would require more duplicate code as list_selectchat_filtered and list_draw already had). Also, search_offset and search_unset gave me headaches.

So this is the new system:

We still have the item list (`ITEM *item`) containing all items.
We now also have a `shown_list`, which contains indexes which point to the items from the `item` list. This is the list we use to find what items are currently visible in the user's list.
`update_shown_list()` updates our `shown_list` based on filter and search settings. It needs to be called whenever something relevant to those things is changed.
You can also use `find_item_shown_index(ITEM *it)` to get the index in the `shown_list` of given item, which is handy when for example, switching to the next or previous item in the list.

This improves things by keeping the filtering in one place(`update_shown_list()`), which creates the `shown_list` which can be used in other functions, without them having to do any filtering or use the "offsets" or "unsets" of the search. Also, we can implement something like qTox' sorting to keep online friends at the top without altering their original location with this. The disadvantage is needing to remember to call update_shown_list after anything relevant changes, but you'd only typically do that when for example adding a new filter. That doesn't happen much, and it'll be obvious that you need to update the list when working on that.

Using this system I created previous/next tab shortcuts on Linux and Windows.
TODO:
 - someone who knows Objective-C can add the shortcuts for OSX
 - make the list scroll up/down automatically when you switch to a friend not immediately visible

### CODE REVIEW

**Comment by stal888** [comment]
cocoa uses control-[0-9] to jump to the Nth friend in the list. you might want to implement those too.

**Comment by GrayHatter** [comment]
Maybe take the quassel approch? Ctrl + \d == set && Alt + \d == switch?

But I have a feeling that's much more complicated, so you can make them both just switch to the current number in the view

**Comment by Doom032** [comment]
I added it now as I see it in the obj-c code(alt/ctrl+0 brings you to first chat, alt/ctrl+1 to next, etc.) but I notice it's a bit weird from a user perspective. Because the 1 is the leftmost number on your keyboard, and the zero the rightmost, I think it should be that alt+1 brings you to the first chat, and alt+0 to the 10th. It makes most sense from a user perspective.

Waiting for @stal888 's opinion on this, because that would require changing obj-c code as well(worst would be that it works differently on both OSes).

**Comment by GrayHatter** [comment]
> Waiting for @stal888 's opinion on this, because that would require changing obj-c code as well(worst would be that it works differently on both OSes).

I'm not strictly opposed to that, but ideally it should be in the case of maintaining OS quirks/style

**Comment by Doom032** [comment]
@GrayHatter Obviously, but I don't think this has to do with OS quirks, I don't know OSX that well but I'd assume it'd also go for the user-friendly(with our keyboards) approach of starting with 1 in such cases, and seeing 0 as 10.

**Comment by stal888** [comment]
@Doom032 Yeah, go ahead and do that. If you add the Alt key please check for an active edit first, because OS X binds Alt-[0-9] to insert symbols.

**Comment by GrayHatter** [comment]
@stal888 @Doom032 that reminded me of another uTox issue. Let's completely drop alt + * unless you can tell me it' mandatory. There's a char insertion error using alt on windows right now that I need to fix before we go messing with alt + key,

**Comment by Doom032** [comment]
As I said in IRC, I think I fixed that issue while working on this. Gonna commit this now.

**Comment by GrayHatter** [comment]
fucket, merged now. Looks good to me

**Pull request merged**
