### PR TITLE
updates and fixes in Ukrainian translation

### PR DESCRIPTION
**Pull request by Yalvex**
[Review on Reviewable](https://reviewable.io/reviews/grayhatter/utox/227)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[langs/ua.h, line 526 \[r1\]](https://reviewable.io:443/reviews/grayhatter/utox/227#-KBt_kNqo_wB3757VPPK:-KBt_kNqo_wB3757VPPL:360616811) ([raw file](https://github.com/grayhatter/utox/blob/5f0b848f55d8c4ad4a7d9d13ab37db7f256e9250/langs/ua.h#L526)):*
you can delete this, it's the same in en.h

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/grayhatter/utox/227)*

**Comment by Yalvex** [comment]
Is it possible not to delete, but comment out?
Just so it's easier to find differences with the English version.

**Comment by GrayHatter** [comment]
Yes that's fine!

I'm going to write a script that will do all of this, so writing translations will stop being so painful.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/grayhatter/utox/227#-:-KBtcFDPVJuKej1BzsF-:1224511753)*

**Comment by GrayHatter** [comment]
this build fails on travis, do you know why?

**Comment by Yalvex** [comment]
Sorry, I don't know.
I'll try to build on a my laptop, maybe it will explain the situation.
Sorry

**Comment by cebe** [comment]
It fails because it is not based on the latest develop branch but on master and there the `WHERE_TO_SAVE_FILE` message key does not exist yet.
Can you rebase this on develop branch?

**Pull request closed without merging**
