### PR TITLE
Add bg and icon to linux tray icon

### PR DESCRIPTION
**Pull request by GrayHatter**
Will merge after 2 others tell me it works.

### CODE REVIEW

**Comment by benwaffle** [comment]
It's just white

**Comment by GrayHatter** [comment]
@benwaffle so it's just a white box, until you click on it, then it gets the uTox logo?

Can I get a screen shot?

**Comment by benwaffle** [comment]
Ok, more specifically, the icon is white when the GNOME tray is hidden, but when I click it to show the window, the icon is drawn. The the tray slides away again it becomes white

**Comment by GrayHatter** [comment]
I have no idea what that means...

**Comment by cebe** [comment]
@GrayHatter could you rebase this on `develop`? I would test it but the code on this branch does not seem to be compatible with the latest toxcore:

```
$ make
  CC    tooltip.o
In file included from tooltip.c:1:0:
main.h:431:1: error: unknown type name ‘ToxAv’
 ToxAv* global_av;
 ^
Makefile:119: recipe for target 'tooltip.o' failed
make: *** [tooltip.o] Error 1
```

**Comment by cebe** [comment]
managed to rebase myself, does not seem to fix #55, so as no icon shows up I can not confirm that it works.

**Comment by GrayHatter** [comment]
@cebe just merged develop as well. Try it again, and gist me the output? Only need when it starts.

**Comment by cebe** [comment]
@GrayHatter on Gnome3 there does not seem to be any tray, so I can not test this.

**Comment by benwaffle** [comment]
GNOME 3.18 added it i think

**Comment by zestyr** [comment]
In XFCE it doesn't even show up, and the icon for the "window button" doesn't work (attached image).
atmbf1o

**Pull request merged**
