### PR TITLE
adding linux screenshot

### PR DESCRIPTION
**Pull request by alugarius**
This change is [Reviewable](https://reviewable.io/reviews/grayhatter/utox/359)

### CODE REVIEW

**Comment by alugarius** [comment]
If thus is added ill update the readme

**Comment by GrayHatter** [comment]
you can do both in the same PR

That's actually what I was waiting on, was for you to update the readme too

**Comment by alugarius** [comment]
oh ok, im not quiet into git

**Comment by alugarius** [comment]
yay ^^

**Comment by GrayHatter** [comment]
merged!

**Pull request closed without merging**
