### PR TITLE
New Interface changes because stal hate's the current.

### PR DESCRIPTION
**Pull request by GrayHatter**

### CODE REVIEW

**Comment by GrayHatter** [comment]
inline

**Comment by tsudoko** [comment]
Looks like elements on the bottom bar need more padding

**Comment by GrayHatter** [comment]
@tsudoko I can't decide If I want to push them up/bigger, or shrink down the chat box....

**Comment by GrayHatter** [comment]
todo; clear tying notification on enter

**Comment by tsudoko** [comment]
Groupchat context menu items seem to be broken.
`Change Topic` crashes when clicked on ([log](https://gist.github.com/tsudoko/e2910ed9b62bb8aadb22)), `Remove Group` does nothing.

**Pull request merged**
